Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2021-02, with the labels that each got.

#294 Ajout d'un message de bienvenue
  components/welcome-message.js
  pages/_app.js
Labels: enhancement, ux

#295 Corrige la mise à jour du nom de la voie après un changement de voie
  pages/bal/voie-heading.js
  pages/bal/voie.js
Labels: bug

#299 Corrections concernant le complément du nom de voie
  components/map/hooks/layers.js
  components/map/layers/voies.js
  components/map/map.js
  pages/bal/voie-heading.js
  pages/bal/voie.js
Labels: bug

#293 Ajouter plusieurs positions à un numéro
  components/bal/address-editor.js
  components/bal/numero-editor.js
  components/bal/position-editor.js
  components/bal/voie-editor.js
  components/grouped-actions.js
  components/map/editable-marker.js
  components/map/map.js
  components/map/numero-marker.js
  components/map/toponyme-marker.js
  components/table-row.js
  contexts/bal-data.js
  contexts/map.js
  contexts/marker.js
  contexts/markers.js
  contexts/token.js
  pages/_app.js
  pages/bal/commune.js
  pages/bal/voie.js
Labels: enhancement
