Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2021-06, with the labels that each got.

#347 Assignation de parcelles cadastrale aux adresses
  components/bal/address-editor.js
  components/bal/numero-editor.js
  components/bal/numero-editor/select-parcelles.js
  components/bal/toponyme-editor.js
  components/help/help-tabs/numeros.js
  components/help/help-tabs/toponymes.js
  components/map/hooks/hovered.js
  components/map/hooks/layers.js
  components/map/hooks/sources.js
  components/map/layers/cadastre.js
  components/map/map.js
  components/map/numero-marker.js
  components/map/style-selector.js
  components/map/styles/index.js
  components/map/styles/ortho.json
  components/map/styles/vector-cadastre.json
  components/map/styles/vector.json
  components/map/toponyme-marker.js
  contexts/bal-data.js
  contexts/map.js
  contexts/parcelles.js
  lib/bal-api/index.js
  pages/_app.js
  pages/bal/commune.js
  pages/bal/toponyme-heading.js
  pages/bal/toponyme.js
  pages/bal/voie.js
Labels: enhancement, feature

#354 Amélioration UX de l’association des parcelles cadastrale
  components/bal/address-editor.js
  components/bal/draw-editor.js
  components/bal/numero-editor.js
  components/bal/numero-editor/select-parcelles.js
  components/bal/position-editor.js
  components/bal/toponyme-editor.js
  components/input-label.js
  components/map/map.js
  components/map/style-selector.js
  contexts/map.js
Labels: enhancement, ux

#349 Ajout d'une alerte si la commune a déjà publiée un Base Adresse Locale
  components/bases-locales-list/base-locale-card.js
  lib/bal-api/index.js
  package.json
  pages/new/alert-published-bal.js
  pages/new/create-form.js
  pages/new/upload-form.js
  yarn.lock
Labels: feature
