Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-02, with the labels that each got.

#471 Intégration de l'API de dépôt
  .env.sample
  components/bal/address-editor.js
  components/base-locale-card/base-locale-card-content.js
  components/base-locale-card/index.js
  components/bases-locales-list/base-locale-card.js
  components/bases-locales-list/index.js
  components/bases-locales-list/public-bases-locales-list.js
  components/dashboard/commune-bal-list.js
  components/habilitation-process/accepted-dialog.js
  components/habilitation-process/authenticated-user.js
  components/habilitation-process/index.js
  components/habilitation-process/rejected-dialog.js
  components/habilitation-process/strategy-selection/code-email.js
  components/habilitation-process/strategy-selection/france-connect.js
  components/habilitation-process/strategy-selection/index.js
  components/habilitation-process/validate-authentication/code-validation.js
  components/habilitation-process/validate-authentication/index.js
  components/habilitation-tag.js
  components/help/help-tabs/communes.js
  components/help/help-tabs/index.js
  components/help/help-tabs/publication.js
  components/help/help-tabs/toponymes.js
  components/help/help-tabs/voies.js
  components/settings.js
  components/settings/settings-form.js
  components/status-badge.js
  components/sub-header/bal-status/ban-sync/ban-history.js
  components/sub-header/bal-status/ban-sync/ban-history/revision-user.js
  components/sub-header/bal-status/ban-sync/ban-history/revision.js
  components/sub-header/bal-status/ban-sync/index.js
  components/sub-header/bal-status/ban-sync/sync-button.js
  components/sub-header/bal-status/index.js
  components/sub-header/bal-status/publication.js
  components/sub-header/bal-status/refresh-sync-badge.js
  components/sub-header/index.js
  components/sub-header/publication.js
  components/sub-header/settings-menu.js
  components/text-wrapper.js
  contexts/bal-data.js
  contexts/settings.js
  lib/bal-api/index.js
  lib/ban-api.js
  lib/statuses.js
  package.json
  pages/_app.js
  pages/bal/commune.js
  pages/bal/index.js
  pages/bal/toponyme-heading.js
  pages/bal/toponyme.js
  pages/bal/voie-heading.js
  pages/bal/voie.js
  pages/bal/voie/numeros-list.js
  pages/new/alert-published-bal.js
  public/static/images/FCboutons-10.svg
  public/static/images/bal-logo.png
  public/static/images/ban-logo.png
  public/static/images/ban-logo.svg
  public/static/images/elu.svg
  public/static/images/mairie.svg
  yarn.lock
Labels: enhancement, ux, feature

#498 Retire le bouton "Publier" en mode démonstration
  components/sub-header/bal-status/index.js
Labels: bug

#493 Remplacer les boutons avec une action de redirection par de vrais liens #491
  components/layout/dashboard.js
  components/sub-header/settings-menu.js
  components/user-bases-locales.js
  pages/404.js
  pages/_error.js
  pages/all.js
  pages/index.js
  pages/new/index.js
  pages/new/upload.js
Labels: enhancement
