Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-08, with the labels that each got.

#635 Correction de la gestion du focus dans le composant <AssistedTextField/>
  components/assisted-text-field.js
  components/langues-regionales-form/language-field.js
Labels: bug

#650 Mise à jour de @ban-team/shared-data vers la version 1.0.1
  package.json
  yarn.lock
Labels: dependencies

#651 Mise à jour de @ban-team/shared-data
  package.json
  public/static/images/flags/cat.svg
  yarn.lock
Labels: do-not-merge

#648 Amélioration du système de focus
  components/accent-tool.js
  components/assisted-text-field.js
  components/bal/numero-editor.js
  components/bal/numero-editor/numero-voie-selector.js
  components/bal/toponyme-editor.js
  components/bal/voie-editor.js
  components/demo-warning.js
  components/langues-regionales-form/language-field.js
  components/new/create-form.js
  components/new/demo-form.js
  components/new/upload-form.js
  hooks/caret-position.js
  hooks/focus.js
Labels: bug, enhancement

#639 Corrige le problème de mise en évidence des parcelles sélectionnées
  components/bal/numero-editor.js
  components/bal/toponyme-editor.js
  components/map/hooks/hovered.js
  components/map/hooks/layers.js
  components/map/hooks/sources.js
  components/map/layers/cadastre.js
  components/map/layers/numeros.js
  components/map/layers/voies.js
  components/map/map.js
  components/map/numero-marker.js
  components/map/numeros-markers.js
  components/map/toponyme-marker.js
  components/voie/numeros-list.js
  contexts/map.js
  contexts/parcelles.js
  pages/bal.js
Labels: bug

#663 Correction de l'édition des numéros d'un toponyme depuis la carte
  hooks/form-state.js
  pages/bal/toponyme.js
  pages/bal/voie.js
Labels: bug

#583 Chargement progressif des éléments d’une liste
  components/bal/address-editor.js
  components/bal/numero-editor.js
  components/bal/toponyme-editor.js
  components/bal/toponymes-list.js
  components/bal/voie-editor.js
  components/bal/voies-list.js
  components/form-container.js
  components/form-master.js
  components/form.js
  components/grouped-actions.js
  components/infinite-scroll-list.js
  components/new/create-form.js
  components/new/demo-form.js
  components/new/upload-form.js
  components/settings/settings-form.js
  components/table-row/index.js
  components/toponyme/toponyme-heading.js
  components/voie/numeros-list.js
  pages/bal.js
  pages/bal/toponyme.js
  pages/bal/voie.js
Labels: enhancement, feature

#677 Corrige le bug du formulaire des paramètres de la BAL
  components/settings/settings-form.js
Labels: bug

#673 Corrige le problème d’affichage des parcelles dans l’éditeur de numéro
  components/bal/numero-editor/select-parcelles.js
Labels: bug

#628 Suppression "Soft"
  lib/bal-api/index.js
Labels: enhancement

#685 Empêcher la publication de BAL sans adresse
  components/sub-header/index.js
  lib/bal-api/index.js
Labels: enhancement, beginner-users

#675 Remplace mapbox-gl par map-libre-gl
  components/map/controls/control.js
  components/map/map.js
  package.json
  pages/_app.js
  yarn.lock
Labels: dependencies
