Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-03, with the labels that each got.

#503 Utilisation de tuiles vectorielle pour la cartographie du dashboard
  components/dashboard/bal-creation-chart.js
  components/dashboard/map.js
  lib/bases-locales.js
  lib/colors.js
  pages/dashboard.js
  pages/dashboard/departement.js
Labels: enhancement, feature

#488 Permet d'enlever une base adresse locale de la liste sans la supprimer
  components/base-locale-card/base-locale-card-content.js
  components/base-locale-card/index.js
  components/bases-locales-list/index.js
  components/hidden-bal.js
  components/user-bases-locales.js
  contexts/local-storage.js
Labels: ux, feature, expert-users

#506 Correction du dossier /pages
  components/new/alert-published-bal.js
  components/new/create-form.js
  components/new/demo-form.js
  components/new/upload-form.js
  components/toponyme/toponyme-heading.js
  components/voie/numeros-list.js
  components/voie/voie-heading.js
  pages/bal.js
  pages/bal/toponyme.js
  pages/bal/voie.js
  pages/dashboard.js
  pages/dashboard/redirection.js
  pages/new.js
  pages/new/upload.js
Labels: enhancement

#512 Correction de l'historique de publication
  components/sub-header/bal-status/ban-sync/ban-history/revision.js
Labels: bug

#477 Refonte du chargement des pages et des contextes
  components/bal/address-editor.js
  components/bal/toponyme-editor.js
  components/bal/toponymes-list.js
  components/bal/voies-list.js
  components/bases-locales-list/index.js
  components/bases-locales-list/public-bases-locales-list.js
  components/help/tuto/sidebar.js
  components/help/tuto/unauthorized.js
  components/map/hooks/layers.js
  components/map/map.js
  components/map/numeros-markers.js
  components/new/create-form.js
  components/new/demo-form.js
  components/settings.js
  components/settings/settings-form.js
  components/sub-header/index.js
  components/toponyme/toponyme-heading.js
  components/voie/numeros-list.js
  components/voie/voie-heading.js
  contexts/bal-data.js
  layouts/dashboard.js
  layouts/editor.js
  layouts/fullscreen.js
  layouts/main.js
  lib/bal-api/index.js
  pages/404.js
  pages/_app.js
  pages/_error.js
  pages/all.js
  pages/bal.js
  pages/bal/commune.js
  pages/bal/toponyme.js
  pages/bal/voie.js
  pages/dashboard.js
  pages/dashboard/departement.js
  pages/index.js
  pages/new.js
Labels: enhancement

#524 Refonte du composant <TableRow />
  components/bal/toponymes-list.js
  components/bal/voies-list.js
  components/table-row.js
  components/table-row/index.js
  components/table-row/table-row-actions.js
  components/table-row/table-row-edit-shortcut.js
  components/table-row/table-row-notifications.js
  components/voie/numeros-list.js
  pages/bal/commune.js
Labels: enhancement
