Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-04, with the labels that each got.

#550 Fix csv import
  components/new/upload-form.js
Labels: bug

#554 Correction du rafraîchissement des données cartographiques
  components/map/numeros-markers.js
  components/voie/numeros-list.js
  pages/bal/voie.js
Labels: bug

#551 Amélioration du système de sélection de numéros pour les toponymes
  components/toponyme/add-numeros.js
Labels: ux, user-feedback

#565 Mise à jour @etalab/bal en v2.4.0
  package.json
  yarn.lock
Labels: dependencies
