Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-06, with the labels that each got.

#603 Corrige l’affichage des commentaires au chargement de la page
  pages/bal/toponyme.js
  pages/bal/voie.js
Labels: bug

#611 Désactive les fonds de carte indisponible sur le territoire
  components/map/controls/style-control.js
  components/map/map.js
Labels: enhancement

#601 Suppression du filtre des Collectivités d’Outre-Mer au formulaire de création
  components/base-locale-card/index.js
  components/commune-search/commune-search.js
  components/new/demo-form.js
Labels: enhancement

#614 Amélioration des espaces sur les contrôleurs de la carte
  components/map/map.js
Labels: ux
