Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-07, with the labels that each got.

#629 Update @etalab/bal
  components/new/upload-form.js
  package.json
  yarn.lock
Labels: dependencies

#633 Mise à jour de @ban-team/validateur-bal
  package.json
  yarn.lock
Labels: dependencies

#631 Ajout, gestion et affichage des langues régionales
  .gitignore
  README.md
  components/accent-tool.js
  components/assisted-text-field.js
  components/bal/language-preview.js
  components/bal/numero-editor.js
  components/bal/toponyme-editor.js
  components/bal/toponymes-list.js
  components/bal/voie-editor.js
  components/bal/voies-list.js
  components/langues-regionales-form/index.js
  components/langues-regionales-form/language-field.js
  components/table-row/index.js
  components/table-row/table-row-edit-shortcut.js
  components/toponyme/toponyme-heading.js
  components/voie/voie-heading.js
  package.json
  public/static/images/flags/bre.svg
  public/static/images/flags/cos.svg
  public/static/images/flags/eus.svg
  public/static/images/flags/fra.svg
  public/static/images/flags/gcf.svg
  public/static/images/flags/gcr.svg
  public/static/images/flags/gsw.svg
  public/static/images/flags/ntr.svg
  public/static/images/flags/oci.svg
  public/static/images/flags/rcf.svg
  public/static/images/flags/swb.svg
  scripts/build-available-flags.js
  yarn.lock
Labels: do-not-merge

#637 Afficher les drapeaux de toutes les langues régionales dispo
  components/bal/language-preview.js
  components/table-row/table-row-edit-shortcut.js
Labels: ux

#642 Correction du rechargement des tracés de voie
  components/bal/voie-editor.js
  components/map/draw.js
  components/voie/voie-heading.js
  contexts/draw.js
Labels: bug

#645 Correction du défilement pour la création d'un toponyme
  components/bal/toponyme-editor.js
  components/toponyme/toponyme-heading.js
  pages/bal.js
  pages/bal/toponyme.js
Labels: bug

#643 Correction du tracé de nouvelles voies
  contexts/draw.js
Labels: bug
