Repository BaseAdresseNationale/mes-adresses, pull requests merged in 2022-09, with the labels that each got.

#666 Gestion des messages d'erreur pour les langues régionales
  components/assisted-text-field.js
  components/bal/toponyme-editor.js
  components/bal/voie-editor.js
  components/langues-regionales-form/index.js
  components/langues-regionales-form/language-field.js
  hooks/validation-messages.js
Labels: enhancement

#691 Corriger le badge de statut "à jour" écrasé des BALs
  components/base-locale-card/index.js
Labels: ux

#700 Indique si les adresses d'une voie sont toutes certifiées
  components/bal/toponymes-list.js
  components/bal/voies-list.js
  components/settings.js
  components/table-row/table-row-notifications.js
  components/voie/numeros-list.js
Labels: do-not-merge

#705 Correction du renouvellement de l'habitation pour les BAL en conflit
  components/sub-header/index.js
Labels: bug

#707 Averti l'utilisateur lorsqu'un grand nombre d'adresse semble avoir été supprimé
  .env.sample
  components/habilitation-process/index.js
  components/mass-deletion-dialog.js
  components/sub-header/bal-status/ban-sync/ban-history.js
  components/sub-header/bal-status/index.js
  components/sub-header/index.js
  lib/api-ban.js
  lib/ban-api-depot.js
Labels: enhancement, beginner-users

#706 Montre les commentaires des adresses dans la liste des voies et des toponymes
  components/bal/toponymes-list.js
  components/bal/voies-list.js
  components/comments-content.js
  components/table-row/table-row-notifications.js
Labels: do-not-merge
